color: null
description: null
fieldLayouts:
  f73678d2-2b29-48d7-99ef-179a914dc502:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-13T13:12:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 39237593-ff51-4bd3-851a-a9dfac329c0b # Page Summary
            handle: socialName
            includeInCards: true
            instructions: null
            label: Name
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04c536c3-f73d-4ca7-85ca-50e0d8acedaa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-13T13:12:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5cd6ad16-cb88-45ba-b275-1558f8f27c05
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba83ae0b-ea3d-40c4-89f3-6d3e8534008b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-13T13:12:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a596aec7-c8ec-49d7-ab4d-97dcdf5ac990
            handle: null
            includeInCards: false
            instructions: null
            label: Icon
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 364eb41b-af94-40cb-bd43-6998de612fdf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-13T13:12:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a596aec7-c8ec-49d7-ab4d-97dcdf5ac990
            handle: altSocialIcon
            includeInCards: false
            instructions: null
            label: 'Alt Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a87003cb-13e7-4241-93ae-af03a9b88cf7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22f55445-1a39-4046-b6c1-a9f2c4fe6690
        userCondition: null
handle: socialProfile
hasTitleField: false
icon: null
name: 'Social Profile'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
