columnSuffix: null
handle: buttonColour
instructions: null
name: 'Button Colour'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - button-black
        -
          - icon
          - ''
        -
          - color
          - '#000000'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - button-white
        -
          - icon
          - ''
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
