columnSuffix: null
handle: customLink
instructions: null
name: Link
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
      -
        - asset
        -
          __assoc__:
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
  types:
    - entry
    - url
    - asset
    - category
    - email
    - tel
    - sms
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
